window.addEventListener('load',()=>document.getElementById('preloader')?.classList.add('done'));
const menu=document.getElementById('sidemenu');function openmenu(){if(menu)menu.style.right='0'}function closemenu(){if(menu)menu.style.right='-100%'}document.querySelectorAll('#sidemenu a').forEach(a=>a.addEventListener('click',closemenu));
function opentab(tabname,button){document.querySelectorAll('.tab-links').forEach(t=>t.classList.remove('active-link'));document.querySelectorAll('.tab-contents').forEach(t=>t.classList.remove('active-tab'));button.classList.add('active-link');document.getElementById(tabname)?.classList.add('active-tab')}
const cursor=document.querySelector('.cursor-glow');if(cursor)window.addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const techTitle=document.getElementById('tech-title'),techInfo=document.getElementById('tech-info');document.querySelectorAll('.tech-node').forEach(node=>node.addEventListener('click',()=>{document.querySelectorAll('.tech-node').forEach(n=>n.classList.remove('active'));node.classList.add('active');if(techTitle)techTitle.textContent=node.dataset.title||'';if(techInfo)techInfo.textContent=node.dataset.info||''}));

// LinkedIn-verified experience. The source screenshot provides title, company, dates, employment type and remote location.
const experienceTimeline=document.querySelector('#experience > .container > .timeline');
if(experienceTimeline){experienceTimeline.innerHTML=`
<article><span>APR 2024 — PRESENT</span><h3>Flutter Developer</h3><p>Innovins Softtech Solutions Pvt. Ltd.</p><p style="margin-top:8px">Full-time · Remote</p></article>
<article><span>JUL 2023 — APR 2024</span><h3>Flutter</h3><p>Nextgen Techno Ventures Private Limited</p><p style="margin-top:8px">Full-time · Remote</p></article>
<article><span>MAY 2023</span><h3>Flutter Developer</h3><p>Celebrare</p><p style="margin-top:8px">Internship · Remote</p></article>
<article><span>MAR 2022 — MAY 2022</span><h3>Flutter Developer</h3><p>Baoiam Innovations Pvt Ltd</p><p style="margin-top:8px">Internship · Remote</p></article>`}

const canvas=document.getElementById('scene'),reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches,small=window.matchMedia('(max-width:800px)').matches;
if(window.THREE&&canvas&&!reduced){const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:!small});renderer.setPixelRatio(Math.min(devicePixelRatio,small?1.25:1.7));const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,100);camera.position.z=7;const group=new THREE.Group();scene.add(group);const points=[],count=small?380:700;for(let i=0;i<count;i++){const r=3.1+Math.random()*1.8,a=Math.random()*Math.PI*2,y=(Math.random()-.5)*4.5;points.push(Math.cos(a)*r,y,Math.sin(a)*r)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(points,3));group.add(new THREE.Points(geo,new THREE.PointsMaterial({color:0x7587ff,size:small?.024:.018,transparent:true,opacity:.62})));const ring=new THREE.Mesh(new THREE.TorusGeometry(1.75,.008,8,160),new THREE.MeshBasicMaterial({color:0x8f7aff,transparent:true,opacity:.32}));ring.rotation.x=1.05;group.add(ring);const ring2=ring.clone();ring2.rotation.x=.5;ring2.rotation.y=.8;ring2.scale.setScalar(1.3);group.add(ring2);function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();let mx=0,my=0;addEventListener('pointermove',e=>{mx=(e.clientX/innerWidth-.5)*.35;my=(e.clientY/innerHeight-.5)*.2});function animate(){requestAnimationFrame(animate);group.rotation.y+=small?.001:.0016;group.rotation.x+=(my-group.rotation.x)*.01;group.position.x+=(mx-group.position.x)*.02;ring.rotation.z+=.0035;ring2.rotation.z-=.0025;renderer.render(scene,camera)}animate()}
if(!small&&!reduced)document.querySelectorAll('.magnetic').forEach(btn=>{btn.addEventListener('pointermove',e=>{const r=btn.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.08,y=(e.clientY-r.top-r.height/2)*.12;btn.style.transform=`translate(${x}px,${y}px)`});btn.addEventListener('pointerleave',()=>btn.style.transform='')});
const scriptURL='https://script.google.com/macros/s/AKfycbyDanjzL5W9wfoXg-QixhMNWHqXovLbfQzAOQLD8syzXeF2jAlDDA4Cyr7dNTDSbAJEag/exec',form=document.forms['submit-to-google-sheet'],msg=document.getElementById('msg');if(form)form.addEventListener('submit',e=>{e.preventDefault();if(msg)msg.textContent='Sending…';fetch(scriptURL,{method:'POST',body:new FormData(form)}).then(()=>{if(msg)msg.textContent='Message sent successfully.';form.reset();setTimeout(()=>{if(msg)msg.textContent=''},5000)}).catch(()=>{if(msg)msg.textContent='Could not send. Please email me directly.'})});
